project_id = "nkrirpjmixfrunhmrawz"

[functions.submit-waste]
verify_jwt = false

[functions.send-confirmation-email]
verify_jwt = false

[functions.register-user]
verify_jwt = false

[functions.check-user]
verify_jwt = false

